### ISSUE TITLE
Plugin interface

### ISSUE THREAD

**Issue by mlotekk** [awslabs/collectd-cloudwatch#27]
I'm running collectd-5.4.1-1.11.amzn1.x86_6. The data is being sent by the cloudwatch_writer and being collected by plugin interface. When I look at if_octets or if_packets.*, the data steadily increments. How can I get this in bytes/sec, rather than a counter from plugin interface? 
I got something like this
![zrzut ekranu z 2016-12-12 16-31-34](https://cloud.githubusercontent.com/assets/10896586/21104887/7ed49d9c-c088-11e6-849a-4a98ef25a55d.png)

**Comment by sebasrp** [comment]
You can get the bytes/sec through the [Interface plugin](https://collectd.org/wiki/index.php/Plugin:Interface).
The plugin is enabled - so check the file` /opt/collectd-plugins/cloudwatch/config/blocked_metrics` and add the desired metrics to `/opt/collectd-plugins/cloudwatch/config/whitelist.conf`
