### ISSUE TITLE
Credentials file doesn't match AWS CLI credentials file.

### ISSUE THREAD

**Issue by aasim** [awslabs/collectd-cloudwatch#28]
The credentials file we generate for the AWSCLI has the format described on this page: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles, however the credentials file that this plugin expects just has:
```
aws_access_key = valid_access_key
aws_secret_key = valid_secret_key
```
without the profile name. It would be nicer if the format of the credentials file followed the previous pattern, that way I wont have to create multiple credentials files.

Aasim

**Comment by berenddeboer** [comment]
Tripped me up too, especially since the installer gives the aws cli one as the default!
