### ISSUE TITLE
How do you handle steadily increasing counters?

### ISSUE THREAD

**Issue by berenddeboer** [awslabs/collectd-cloudwatch#29]
collectd has lots of plugins that collect steadily increasing counters, insert commands in mysql for example, or varnish cache hits. They just keep increasing in the CloudWatch Management Console, what I need is a changing value over time. How do you do that?

I.e. what I want to see in the console are derivatives (i.e. DERIVE as per types.db).

**Comment by sebasrp** [comment]
Hi,
This is really more to do with collectd itself than with the plugin, but this is my current understanding of what you can do to go around this problem:
* Use the [Aggregation Plugin](https://collectd.org/wiki/index.php/Plugin:Aggregation)
* Use the [Chain plugin](https://collectd.org/wiki/index.php/Chains)

Ultimately I would reach out to the wider collectd community [see contact information](https://collectd.org/contact.shtml)
