### ISSUE TITLE
Cloudwatch logs vs Logstash

### ISSUE THREAD

**Issue by rajasekaran07** [awslabs/collectd-cloudwatch#30]
Hi Team,

It is a kind question. I am just curious to know why logstash is the best tool to send logs to elasticsearch. We are running our all applications in AWS so, we are planning to use AWS Cloudwarch logs to collect and send application logs to elasticsearch. please give some suggestion for best practices.

Regards,
Raja

**Comment by sebasrp** [comment]
Hi,
Thanks for your question. Since the question does not relate directly to this repository, I'm going to close it.
I recommend submitting this question here: https://github.com/awslabs/logstash-output-cloudwatchlogs
