### ISSUE TITLE
Allow for non-interactive installations.

### ISSUE THREAD

**Issue by joestump** [awslabs/collectd-cloudwatch#33]
Currently, it doesn't appear easily possible to install this using traditional automation tooling. The [CloudWatch Logs installer](https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py) allows for a non-interactive mode to help with this (though I'd still argue it's pretty convoluted to install via automation).

Alternatively, provide documentation to install manually without using the `setup.py` script at all.

**Comment by mseiwald** [comment]
I'm using this workaround: (might have to adapt to your situation)

    printf '\n\n\n\n' | sudo ./setup.py

**Comment by MaDCaTZA** [comment]
I provided a pretty decent fully automated example in this thread that may be of use to you - https://github.com/awslabs/collectd-cloudwatch/issues/5

**Comment by sebasrp** [comment]
closing as duplicate of issue #5
