### ISSUE TITLE
Any way to do an unattended install?

### ISSUE THREAD

**Issue by bunchjesse** [awslabs/collectd-cloudwatch#5]
I want to add this to my user data script that is run when an EC2 instance boots but I'm not seeing a way to do an unattended install. It is asking me to choose an AWS region:

```
root@ip-10-0-0-157:~# curl -L https://github.com/awslabs/collectd-cloudwatch/raw/master/src/setup.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0   3461      0 --:--:-- --:--:-- --:--:--  3500
100 25246  100 25246    0     0   281k      0 --:--:-- --:--:-- --:--:--  281k
Installing dependencies ... OK
Installing python dependencies ... OK
Downloading plugin ... OK
Extracting plugin ... OK
Moving to collectd plugins directory ... OK
Copying CloudWatch plugin include file ... OK

Choose AWS region for published metrics:
  1. Automatic [us-east-1]
  2. Custom
Enter choice [1]: Traceback (most recent call last):
  File "<stdin>", line 586, in <module>
  File "<stdin>", line 579, in main
  File "<stdin>", line 504, in install_plugin
  File "<stdin>", line 520, in supply_config
  File "<stdin>", line 534, in _prepare_plugin_config
  File "<stdin>", line 304, in run
  File "<stdin>", line 313, in _configure_region
  File "<stdin>", line 404, in run
  File "<stdin>", line 407, in _get_answer
EOFError: EOF when reading a line

```

**Comment by rilindo** [comment]
Not sure why there some confusion.  Manually running the script is a big pain, as makes automation extremely difficult (whether by invoking directly through automation tools or via baked images). I second the motion for unattended installation.

**Comment by JadyLiu** [comment]
same request to install unattended. 
Also, getting error when running ./setup.py

Traceback (most recent call last):
  File "<stdin>", line 26, in <module>
ImportError: cannot import name check_output

**Comment by extraordinaire** [comment]
Might help someone:

```
(echo "1"; echo "1"; echo "1"; echo "3"; cat) | sudo ./setup.py
```

**Comment by den-is** [comment]
+1
command line options or external config file supplied in cmd might help a lot.
especially for nodes deployed via auto scaling groups, and if not asg then hosts provisioned by either configuration management system

**Comment by stacyhorton** [comment]
+1 for unattended support please.

**Comment by MaDCaTZA** [comment]
Hey guys,

For those of you wanting to automate this on AWS, here is a sample bootstrap script I have built for my Amazon Linux instance launches and it is working great:

------- Once Off Preparations -------

1.) Rather not fetch the file from Github via your script, instead copy the setup.py raw text into a new text document called setup.py, and upload this to an AWS S3 bucket; Then set this file to be PUBLIC and fetch from there going forward inside your automation scripts. This gives you more ability to control versions of your setup.py file as well as avoiding the "Traceback" error bunchjesse and JadyLiu experienced when downloading and executing straight from Github.

2.) Once the file is in your personal bucket, for example the path to this file may be https://s3-eu-west-1.amazonaws.com/my-bucket-name/setup.py , edit the bash script line 5 and replace the URL there next to wget.

3.) Add the below script to your AWS Autoscaling Launch Configurations, Advanced options (user data).

Notes: Region will be automatically detected, host-name will be set to the instance ID, and IAM Role will be automatically used. For demonstration purposes, only the memory--memory-used OS metric will be pushed to CloudWatch.

------- Bash Script Example -------

#!/bin/bash
yum update -y
yum install collectd -y
cd /tmp
wget https://s3-eu-west-1.amazonaws.com/my-bucket-name/setup.py
sudo chmod a+x setup.py
(echo "1"; echo "1"; echo "1"; echo "2"; cat) | python setup.py
echo "memory--memory-used" > /tmp/whitelist.conf
cp -vrf /tmp/whitelist.conf /opt/collectd-plugins/cloudwatch/config/whitelist.conf
chown root:root /opt/collectd-plugins/cloudwatch/config/whitelist.conf
chmod 644 /opt/collectd-plugins/cloudwatch/config/whitelist.conf
service collectd restart

------------------------------------

**Comment by adjourn** [comment]
I use latest Amazon Linux AMI, collectd version is `5.7.1-3.19.amzn1`. Setup fails.


After digging into this, I realized that configuration has changed a lot, here's what I did:

```
(echo "1"; echo "1"; echo "1"; echo "1"; ecyho "1"; echo "1"; echo "1"; echo "2"; echo "1"; echo "3"; cat) | python setup.py

[1] get region automatically
[1] get EC2 instance id automatically
[1] choose IAM role
[1] no proxy server name
[1] no proxy server port
[1] no ASG metrics
[1] no fixed metric dimension
[2] no high resolution metrics
[1] default flush interval (60s)
[3] use CloudWatch recommended configuration (4 metrics)
```

But I still get the following response:

```
...
Enter choice [3]: Plugin configuration written successfully.
Stopping collectd process ... NOT OK
Starting collectd process ... NOT OK
Installation cancelled due to an error.
Executed command: '/usr/sbin/collectd'.
Error output: ''.
```
`plugin.conf` still messed up, `blocked_metrics`, `whitelist.conf` are empty and `/var/log/messages`:

```
Oct  3 15:30:04 ip-10-10-5-245 collectd[8532]: plugin_load: plugin "syslog" successfully loaded.
Oct  3 15:30:04 ip-10-10-5-245 collectd[8532]: plugin_load: plugin "cpu" successfully loaded.
Oct  3 15:30:04 ip-10-10-5-245 collectd[8532]: plugin_load: plugin "interface" successfully loaded.
Oct  3 15:30:04 ip-10-10-5-245 collectd[8532]: plugin_load: plugin "load" successfully loaded.
Oct  3 15:30:04 ip-10-10-5-245 collectd[8532]: plugin_load: plugin "memory" successfully loaded.
Oct  3 15:30:04 ip-10-10-5-245 collectd[8532]: plugin_load: plugin "python" successfully loaded.
Oct  3 15:30:04 ip-10-10-5-245 collectd[8532]: Looking up "ip-10-10-5-245" failed. You have set the "FQDNLookup" option, but I cannot resolve my hostname to a fully qualified domain name. Please fix the network configuration.
```

`ip-10-10-5-245` seems to be first part of private DNS `ip-10-10-5-245.<region>.compute.internal`.

Any ideas? I have no idea how to resolve this.

**Comment by yimuniao** [comment]
Refer to https://github.com/awslabs/collectd-cloudwatch/pull/52
