### ISSUE TITLE
Could not send processes plugin data to cloudwatch

### ISSUE THREAD

**Issue by kkomazakii** [awslabs/collectd-cloudwatch#59]
Does collectd-cloudwatch plugin not suppurt processes plugin?

I want to monitor my application's process and set alert on cloudwatch.
So I made processes plugin enable and edit conf like below, and confirmed collectd
output rrd file under `/var/lib/collectd/rrd/`.

```
LoadPlugin processes
...
LoadPlugin rrdtool
...
<Plugin processes>
	ProcessMatch "myapp" "myapp"
</Plugin>
...
<Plugin rrdtool>
	DataDir "/var/lib/collectd/rrd"
	CreateFilesAsync false
	CacheTimeout 120
	CacheFlush   900
	WritesPerSecond 50
</Plugin>
```

On cloudwatch metrics, only default metrics were shown and processes data did not appear like this.

![image](https://user-images.githubusercontent.com/31602910/32712598-d75ddf56-c888-11e7-9538-e122e86d1da8.png)

**Comment by Fodoj** [comment]
You need to whitelist process metrics in cloudwatch plugin config file. I can confirm that this plugin works with processes plugin, I did it just two weeks ago :)

**Comment by Fodoj** [comment]
Look for this folder on your server: https://github.com/awslabs/collectd-cloudwatch/tree/master/src/cloudwatch/config

blocked_metrics has a dynamic list of all available but not whitelisted metrics. Whitelist.conf has a list of metrics that actually will be sent to cloudwatch.

**Comment by kkomazakii** [comment]
@Fodoj Thank you for reply.
I'll try it!

I have to add processes to whitelist while it is not listed on blocked_metrics?

**Comment by Fodoj** [comment]
It doesn’t matter if it’s in blocked metrics. As long as it’s whitelisted, it will go through.

**Comment by kkomazakii** [comment]
@Fodoj Thank you for kindness.
I could monitor process count as I wanted!

**Comment by taith-agiletech** [comment]
@kkomazakii 
I'm sorry but, I'm stuck here too.
How did you add to the whitelist?
